Create productvisie.md
VNG-Realisatie/Haal-Centraal pull request #1
Opened 2020-10-16 14:15 UTC by melsk-r

Bevat alles wat de productvisie documenten van BRK bevragen en BRP bevragen ook bevatten behalve de specifiek de voor die API bedoelde delen.
Bij de versie van de BRP bevragen wordt overigens gesproken over 'BDD scenario's' terwijl bij die van de BRK bevragen spreekt over features. Ik heb de laatste term aangehouden er vanuitgaand dat met beide hetzelfde werd bedoelt.

2020-10-19 07:22 UTC, JohanBoer requested changes
Volgens mij heb je een oude versie van de BRP Product Vision gebruikt. De versie die Cathy op 12 augustus op de master heeft gezet is de meest recente versie . 

Daarin wordt overigens in de uitgangspunten nog geredeneerd over de API en URI strategie van het DSO. Dat moet nu natuurlijk gewoon de landelijke API-strategie zijn.

2020-10-20 07:24 UTC, melsk-r commented
Zo te zien heb ik hierin slechts het laatste deel van beide productvisie documenten opgenomen. Dat is natuurlijk niet correct. Ik ga dat corrigeren.

2020-10-20 08:07 UTC, CathyDingemanse commented
> Zo te zien heb ik hierin slechts het laatste deel van beide productvisie documenten opgenomen. Dat is natuurlijk niet correct. Ik ga dat corrigeren.

Ha Robert, ik wil graag e.e.a. updaten, dus laat mij dat maar doen!

2020-10-20 08:45 UTC, melsk-r commented
Top, ik neem aan dat je dat dan in deze repo doet en dat je in de andere repo's de afwijkingen op dit document documenteert.
Ga ik me richten op de andere naar deze repo te verplaatsen documenten.

2020-10-20 14:45 UTC, CathyDingemanse commented
@melsk-r Ik heb de product visie aangepast. 

Ik stel voor om vanaf de andere repo's de volgende zaken te verplaatsen:
- planning
- definition of ready 
- definition of done
- hoe kunt u bijdragen? 
- omgangsvormen 
- design decisions

Ik wil wil graag zelf invulling geven aan de content hiervan. Dat geldt ook voor de content van "hoe kunt u bijdragen?" en "omgangsvormen". Hierin staan teksten die niet op Haal Centraal van toepassing zijn.

2020-10-21 06:50 UTC, melsk-r commented
Prima, laat ik het overzetten van de genoemde documenten aan jou over.

2020-11-03 07:52 UTC, merged